export const GET_WORK = 'GET_WORK';
export const GET_WORK_SUCCESS = 'GET_WORK_SUCCESS';
export const GET_WORK_FAILURE = 'GET_WORK_FAILURE';

export const CLOCK_IN_OUT = 'CLOCK_IN_OUT';
export const CLOCK_IN_OUT_SUCCESS = 'CLOCK_IN_OUT_SUCCESS';
export const CLOCK_IN_OUT_FAILURE = 'CLOCK_IN_OUT_FAILURE';

export const GET_CLOCK_STATUS = 'GET_CLOCK_STATUS';
export const GET_CLOCK_STATUS_SUCCESS = 'GET_CLOCK_STATUS_SUCCESS';
export const GET_CLOCK_STATUS_FAILURE = 'GET_CLOCK_STATUS_FAILURE';