export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_FAILURE = 'GET_ALL_COURSES_FAILURE';

export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAILURE = 'GET_COURSE_FAILURE';

export const SNED_MARK_COURSE = 'SNED_MARK_COURSE';
export const SNED_MARK_COURSE_SUCCESS = 'SNED_MARK_COURSE_SUCCESS';
export const SNED_MARK_COURSE_FAILURE = 'SNED_MARK_COURSE_FAILURE';

